ministryofjustice/nvvs-devops

config/tech-docs.yml

:sparkles: edit tech-docs.yml for github pages following Template Documentation Site

:sparkles: edit tech-docs.yml for github pages

---

.github/workflows/ISSUE_TEMPLATE/story-template.md

To allow tickets to be created by template

:sparkles: Add Github Issue template

---

source/documentation/team-guide/scripts/AddSecret.sh
source/documentation/team-guide/scripts/AddSecureSecret.sh
source/documentation/team-guide/scripts/rds_delete.sh
source/documentation/team-guide/scripts/s3_delete.sh
source/documentation/team-guide/useful-scripts.html.md.erb
source/index.html.md.erb

adds scripts in a new path called `scripts`
adds a new item in internal guidance on main page
lists and provides links to the scripts from a new page called `useful scripts`

:sparkles: Adds useful scripts in team guidance

---

source/index.html.md.erb

We won't be just made up of engineers, reworded but looking for ideas

:art: make intro to cloud ops more inclusive

---

source/documentation/general-information/our-alliance.html.md.erb
source/documentation/general-information/our-ceremonies.html.md.erb
source/documentation/general-information/our-team.html.md.erb
source/documentation/team-guide/best-practices/github.html.md.erb
source/documentation/team-guide/best-practices/jira.html.md.erb
source/documentation/team-guide/best-practices/signing-github-commits.html.md.erb
source/documentation/team-guide/best-practices/tdd.html.md.erb
source/documentation/team-guide/developing-on-a-branch.html.md.erb
source/documentation/team-guide/joining-cloud-ops-team.html.md.erb
source/documentation/team-guide/our-best-practices.html.md.erb
source/documentation/team-guide/team-tools.html.md.erb
source/documentation/team-guide/useful-scripts.html.md.erb
source/index.html.md.erb

Add review dates to all our pages so we know when they are out of date.
---
title: Page Title
last_reviewed_on: 2021-11-09
review_in: 3 months
---

Add page reviews and all repo link

---

architecture-decision-record/000-record-architecture-decisions.md
architecture-decision-record/001-use-bind-for-device-domain-naming-system.md
architecture-decision-record/002-use-cloud-platform-for-hosting.md
architecture-decision-record/002-use-cloud-platform-to-host-dhcp-dns.md
architecture-decision-record/003-use-aws-elastic-container-service-for-dhcp-dns.md
architecture-decision-record/README.md

Add ADRs for DHCP DNS hosting, and main ADR README.md 🍶

📝 Add ADR for hosting DHCP DNS

---

README.md

Move badge under title
*before*
*after*

🎨  Move compliancy badge under title

---

architecture-decision-record/006-use-aws-parameter-store-for-secrets.md
architecture-decision-record/README.md

This adds architectural decision on which secrets management solution we use.

📝 Add adr for secrets management

---

source/index.html.md.erb
source/runbooks/add-a-runbook.html.md.erb

Add a runbook to add a runbook 👀

:memo: Add add-runbook

---

README.md

Correct staff-device-logging-dns-dhcp-integration-tests url

:pencil2: fix url

---

source/index.html.md.erb
source/runbooks/disaster-recovery.html.md.erb

Add disaster recovery section and guide as per issue https://github.com/ministryofjustice/cloud-operations/issues/47

📝 Add DR runbook section and guide

---

source/documentation/general-information/our-alliance.html.md.erb

Refine our alliance based on the workshop and miro board closes #33

:memo: Update our alliance page

---

source/runbooks/disaster-recovery.html.md.erb

Add links to the recovery repository for network access control

:memo: Add disaster recovery for nacs

---

source/index.html.md.erb

:dog: Page reviewed!

---

README.md

- add tech docs notifier https://github.com/ministryofjustice/cloud-operations/issues/32
- change the formatting of repositories

📝  Update README.md

---

source/documentation/general-information/our-ceremonies.html.md.erb
source/documentation/team-guide/best-practices/github.html.md.erb
source/documentation/team-guide/best-practices/zenhub.html.md.erb
source/documentation/team-guide/developing-on-a-branch.html.md.erb
source/documentation/team-guide/joining-cloud-ops-team.html.md.erb
source/documentation/team-guide/our-best-practices.html.md.erb
source/documentation/team-guide/team-tools.html.md.erb
source/runbooks/disaster-recovery.html.md.erb

:monocle_face: Update review dates, review update channel for 🐶

---

.github/workflows/issue-to-project.yml

updated add issue to project to run on workflow call.

update add issues to project workflow

---

.github/workflows/issue-to-project.yml

add-token-input-to-workflow

---

architecture-decision-record/011-use-github-actions-for-ci-cd.md

📝 Update emoji to accepted

---

source/documentation/general-information/our-sprints.html.md.erb

- Update review date
- Add previous results
- Add previous additional outcomes
- Add new goals

🏆 Add sprint 22/06 goals

---

source/documentation/general-information/our-ceremonies.html.md.erb

Update refinement to reflect thursday afternoons rather than monday mornings. Update grooming to reflect monday mornings.

:memo: Update Refinement and Grooming days and times.

---

source/documentation/general-information/our-sprints.html.md.erb

Correcting current sprint start and end dates.

Correcting Sprint Start End Dates

---

source/documentation/general-information/our-sprints.html.md.erb

updating sprint goal outcome and adding a new sprint goal.

:memo: Update Our Sprint Goal

---

source/documentation/general-information/our-alliance.html.md.erb
source/documentation/team-guide/best-practices/signing-github-commits.html.md.erb
source/documentation/team-guide/best-practices/tdd.html.md.erb
source/documentation/team-guide/best-practices/use-aws-sso.html.md.erb
source/documentation/team-guide/useful-scripts.html.md.erb

:memo: Reviewed Daniel the Manual Spaniel Alerts

---

source/runbooks/disaster-recovery.html.md.erb

https://github.com/ministryofjustice/staff-infrastructure-smtp-relay-server/pull/33

📝 Add link to SMTP DR information

---

source/documentation/general-information/our-sprints.html.md.erb

update latest sprint goal information.

:memo: Update Sprint Goal

---

source/documentation/products/dns.html.md.erb
source/documentation/products/product-monitoring-alerting.html.md.erb
source/index.html.md.erb

- Adds a guide to all dashboards and alert channels
- Updates DNS page with links to guide

Add monitoring and alerting guide

---

source/documentation/general-information/our-sprints.html.md.erb

:memo: update-sprint-review-date

---

source/documentation/adrs/000-record-architecture-decisions.html.md.erb
source/documentation/adrs/001-use-bind-for-device-domain-naming-system.html.md.erb
source/documentation/adrs/002-use-cloud-platform-to-host-dhcp-dns.html.md.erb
source/documentation/adrs/003-use-aws-elastic-container-service-for-dhcp-dns.html.md.erb
source/documentation/adrs/004-use-aws-codepiplines-for-cicd.html.md.erb
source/documentation/adrs/005-use-log-aggregration-platform-for-logging.html.md.erb
source/documentation/adrs/006-use-aws-parameter-store-for-secrets.html.md.erb
source/documentation/adrs/007-use-prometheus-and-grafana-for-metrics-alerting.html.md.erb
source/documentation/adrs/008-use-aws-elastic-container-registry.html.md.erb
source/documentation/adrs/009-use-aws-sso-for-aws-account-access.html.md.erb
source/documentation/adrs/010-use-aws-eks-for-monitoring-infrastructure.html.md.erb
source/documentation/adrs/011-use-github-actions-for-ci-cd.html.md.erb
source/documentation/adrs/012-use-techdocs-for-adrs.html.md.erb
source/documentation/adrs/adr-index.html.md.erb

Copy pasta error which meant the `title` did not reflect the page

:memo: Update titles for tech-doc-monitor

---

source/documentation/products/backups.html.md.erb
source/documentation/team-guide/tagging-resources.html.md.erb
source/index.html.md.erb

Adds information on our backup and guidance on tagging resources

📝 Add backup and tagging pages

---

source/index.html.md.erb

Split out internal guidance and getting started on index.html

:memo: Add new section for getting started on the team

---

source/documentation/general-information/our-sprints.html.md.erb

- For Sprint 14/09/2022 - 27/09/2022

🏃‍♀️ update sprint goal

---

source/documentation/team-guide/joining-cloud-ops-team.html.md.erb

Add information for new joiners and starts a reading list.

📝 Add New Joiner reading and information

---

source/documentation/general-information/our-sprints.html.md.erb

Completed past sprint outcomes and updated with the new sprint goals.

:memo: Updated our sprints

---

source/documentation/team-guide/joining-cloud-ops-team.html.md.erb

slack channel name needs to be updated when changed.

📝updated sprint routine

---

.github/ISSUE_TEMPLATE/story-template.yml
.gitignore
README.md
architecture-decision-record/README.md
config/tech-docs.yml
source/documentation/adrs/000-record-architecture-decisions.html.md.erb
source/documentation/adrs/adr-index.html.md.erb
source/documentation/general-information/our-ceremonies.html.md.erb
source/documentation/products/product-monitoring-alerting.html.md.erb
source/documentation/team-guide/joining-cloud-ops-team.html.md.erb
source/index.html.md.erb

This PR updates the team name _Cloud Operations_ to _NVVS DevOps_.
I have not updated references to all Slack channels yet as they still need to be updated and so does the repository name itself. A further PR will be raised to do these when this is done. This means the changes in this PR _should_ not break anything.

📝 Update Team Name

---

architecture-decision-record/README.md
source/documentation/adrs/000-record-architecture-decisions.html.md.erb
source/documentation/general-information/our-ceremonies.html.md.erb
source/documentation/team-guide/best-practices/zenhub.html.md.erb
source/documentation/team-guide/joining-nvvs-devops-team.html.md.erb
source/index.html.md.erb

fix broken links and update zenhub workspace URL

:rotating_light: Fix Broken Links

---

source/documentation/team-guide/best-practices/signing-github-commits.html.md.erb
source/documentation/team-guide/best-practices/tdd.html.md.erb
source/documentation/team-guide/best-practices/use-aws-sso.html.md.erb
source/index.html.md.erb

reviewed pages flagged by daniel the manual spaniel

:memo: Review Team GitHub Pages

---

source/documentation/general-information/our-sprints.html.md.erb
source/documentation/team-guide/joining-nvvs-devops-team.html.md.erb

📝 Update Last Reviewed Dates

---

source/documentation/products/backups.html.md.erb
source/index.html.md.erb

Also remove backup retention statement which is no longer accurate.

📝 Correct monitoring URLs

---

source/documentation/general-information/our-team.html.md.erb

📝Update Team Members

---

source/documentation/general-information/our-sprints.html.md.erb

update sprint with latest goals / results.

:memo: Update Sprint Page

---

source/documentation/general-information/our-sprints.html.md.erb
source/runbooks/creating-github-pat.html.md.erb

Update Sprint Review Date & Creating a GitHub Pat review date.

:memo: Update Sprint Review Date & Creating a GitHub Pat

---

source/documentation/general-information/our-ceremonies.html.md.erb

Hi team 👋 
Noticed a typo in the old documentation there!

:pencil2: Fix Typo in our-ceremonies.html.md.erb

---

source/documentation/adrs/000-record-architecture-decisions.html.md.erb
source/documentation/general-information/our-sprints.html.md.erb
source/documentation/products/product-monitoring-alerting.html.md.erb
source/documentation/team-guide/team-onboarding-checklist.html.md.erb
source/runbooks/creating-github-pat.html.md.erb

Pagea have been reviewed and updated where necessary

Daniel manual spaniel

---

source/documentation/team-guide/best-practices/zenhub.html.md.erb
source/documentation/team-guide/developing-on-a-branch.html.md.erb
source/documentation/team-guide/our-best-practices.html.md.erb
source/documentation/team-guide/team-tools.html.md.erb
source/documentation/team-guide/useful-scripts.html.md.erb

Reviewed & updated these pages

---

source/documentation/general-information/our-ceremonies.html.md.erb

Update our-ceremonies to reflect current ceremony timings, and tools

---

.github/workflows/check-links.yml
.github/workflows/publish.yml
makefile

- This is to address CSS vulnerability found in previous versions

updating tech-docs monitor to version 3.0.1

---

.github/workflows/label-pull-request.yml

Reverts ministryofjustice/nvvs-devops#546

Revert "⬆️ Bump actions/labeler from 4 to 5"

---

.github/workflows/publish.yml

Deploy test failed so reverting back to old version.

Reverting back to old version due to failed test

---

.github/workflows/publish.yml

- Amended publish.yml.
- Split yml into build and publish stages.
- Corrected syntax inline with documentation (https://github.com/ministryofjustice/tech-docs-github-pages-publisher/tree/main)

Nd 92 publisher

---

source/documentation/general-information/our-ceremonies.html.md.erb

Updated to reflect current processes, timings and tools

Update our ceremonies ND-295

---

source/documentation/products/dhcp.html.md.erb
source/documentation/products/dns.html.md.erb
source/documentation/products/nacs.html.md.erb

Pages fine, increased review period to 6 months from 3

---

source/documentation/adrs/001-use-bind-for-device-domain-naming-system.html.md.erb
source/documentation/adrs/002-use-cloud-platform-to-host-dhcp-dns.html.md.erb
source/documentation/adrs/003-use-aws-elastic-container-service-for-dhcp-dns.html.md.erb
source/documentation/adrs/004-use-aws-codepiplines-for-cicd.html.md.erb
source/documentation/adrs/006-use-aws-parameter-store-for-secrets.html.md.erb
source/documentation/adrs/007-use-prometheus-and-grafana-for-metrics-alerting.html.md.erb
source/documentation/adrs/008-use-aws-elastic-container-registry.html.md.erb
source/documentation/adrs/009-use-aws-sso-for-aws-account-access.html.md.erb
source/documentation/adrs/010-use-aws-eks-for-monitoring-infrastructure.html.md.erb
source/documentation/adrs/011-use-github-actions-for-ci-cd.html.md.erb
source/documentation/adrs/012-use-techdocs-for-adrs.html.md.erb
source/documentation/adrs/adr-index.html.md.erb
source/documentation/products/backups.html.md.erb

Pages reviewed.

---

source/documentation/adrs/005-use-log-aggregration-platform-for-logging.html.md.erb

No changed expected or accepted ADRs, therefore more frequent review is unnecessary

Updating review period

---

source/runbooks/creating-github-pat.html.md.erb

Updated the review date to reflect the Review & update for the Generating GitHub PAT page

Updated the review date

---

source/runbooks/creating-github-pat.html.md.erb

Corrected the review date format which was failing the build

Corrected the review date

---

source/runbooks/creating-github-pat.html.md.erb

Nd 306 review update generating git hub pat

---

source/documentation/team-guide/best-practices/jira.html.md.erb

I don't have merge authority so please merge too

Updated review period and last_reviewed date

---

source/documentation/team-guide/best-practices/use-aws-sso.html.md.erb
source/runbooks/creating-github-pat.html.md.erb

Updated the Generate a GPG key section to reflect the current steps

Nd 468 review re configure aws vault page

---

source/index.html.md.erb
source/runbooks/add-new-github-repo-checklist.html.md.erb

Added new runbook for adding new GitGub Repository

---

source/index.html.md.erb
source/runbooks/add-new-github-repo-checklist.html.md.erb

Incorporate feed back in add git repo runbook.

---

source/runbooks/add-new-github-repo-checklist.html.md.erb

Making one step clearer in add github repo

---

source/documentation/general-information/our-sprints.html.md.erb

This is a candidate for archiving when we move across to Confluence

Updated last reviewed date, removed "review in" section.

---

.gitignore
makefile
report-for-daniel-the-manual-spaniel.sh

Amend output to reduce unnecessary confusion.
Add report to text file.

Fix report text

---

source/documentation/team-guide/best-practices/github.html.md.erb
source/documentation/team-guide/best-practices/use-aws-sso.html.md.erb
source/documentation/team-guide/team-onboarding-checklist.html.md.erb

Added details on how new starters can get access to some of the things we use.

Updated onboarding process pages

---

source/documentation/team-guide/team-onboarding-checklist.html.md.erb
source/documentation/team-guide/team-tools.html.md.erb

Added signed commits links under team tools and few corrections

added signed commits links and few corrections

---

source/documentation/adrs/003-use-aws-elastic-container-service-for-dhcp-dns.html.md.erb

also increased review period to 12m

ND-609 no changes to content, review date modified

---

source/runbooks/disaster-recovery.html.md.erb

Period reduced as the content of this page is fine, but we need to run firedrills on DHCP and NACS to confirm their validity.

ND-609 no changes to content, review date modified and period reduced

---

CONTRIBUTING.md
docs/CODE_OF_CONDUCT.md

https://dsdmoj.atlassian.net/browse/ND-638

Added code of conduct and contributing rules

---

source/documentation/adrs/011-use-github-actions-for-ci-cd.html.md.erb

Update last review date

---

source/documentation/team-guide/best-practices/jira.html.md.erb

Added information on the templates we use.

Update to Jira practices

---

source/documentation/team-guide/our-best-practices.html.md.erb

changed date only

---

source/index.html.md.erb

ND-751
removed contact us, left the slack channel 
updated team name
caveat added to SMTP and PKI re offboarding plans

Updates to reflect team

---

source/runbooks/add-new-github-repo-checklist.html.md.erb
source/runbooks/infra-ci-migrate-to-github.html.md.erb

Reviewed the documentation and no updates requited.
Updated the review date.

 Reviewed documentation and updated the review date

---

source/documentation/team-guide/joining-nvvs-devops-team.html.md.erb
source/documentation/team-guide/team-onboarding-checklist.html.md.erb
source/runbooks/add-new-github-repo-checklist.html.md.erb
source/runbooks/creating-github-pat.html.md.erb
source/runbooks/infra-ci-migrate-to-github.html.md.erb

Reviewed and updated below pages
- [Infrastructure CI Migration to GitHub Actions](https://ministryofjustice.github.io/nvvs-devops/runbooks/creating-github-pat.html)
- [Onboarding Checklist](https://ministryofjustice.github.io/nvvs-devops/documentation/team-guide/team-onboarding-checklist.html)
- [Joining the LAN/WiFi-DevOps team](https://ministryofjustice.github.io/nvvs-devops/documentation/team-guide/joining-nvvs-devops-team.html)

Reviewed documentation and updated the review date

---

source/documentation/team-guide/best-practices/tdd.html.md.erb

I challenge the value of this page

changed line 4, no further changes
